# Generated by Django 5.1.4 on 2026-07-27 06:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=12)),
                ('range_key', models.CharField(choices=[('7d', '7 days'), ('30d', '30 days'), ('all', 'All time')], max_length=3)),
                ('timezone', models.CharField(max_length=64)),
                ('stats_hash', models.CharField(max_length=64)),
                ('stats_payload', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64, null=True)),
                ('error_detail', models.TextField(blank=True, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='insight_req_user_created')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'completed')), fields=('user', 'stats_hash'), name='unique_completed_insight_per_user_stats_hash')],
            },
        ),
    ]
