# Generated by Django 5.1.4 on 2026-06-22 06:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('focus_minutes', models.PositiveSmallIntegerField(default=25)),
                ('break_minutes', models.PositiveSmallIntegerField(default=5)),
                ('long_break_minutes', models.PositiveSmallIntegerField(default=15)),
                ('cycle', models.PositiveSmallIntegerField(default=4)),
                ('active_template_label', models.CharField(default='Classic', max_length=100)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='dark', max_length=10)),
                ('sound_enabled', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('focus', models.PositiveSmallIntegerField()),
                ('short_break', models.PositiveSmallIntegerField()),
                ('long_break', models.PositiveSmallIntegerField()),
                ('cycle', models.PositiveSmallIntegerField()),
                ('is_builtin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['label'],
                'constraints': [models.UniqueConstraint(fields=('user', 'label'), name='unique_template_label_per_user')],
            },
        ),
    ]
