# Generated by Django 5.1.4 on 2026-06-22 12:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                            ("extended", "Extended"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("focus", "Focus"),
                            ("break", "Break"),
                            ("longBreak", "Long Break"),
                        ],
                        max_length=10,
                    ),
                ),
                ("template_label", models.CharField(max_length=100)),
                ("session_count", models.PositiveSmallIntegerField()),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("minutes_added", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("client_id", models.CharField(max_length=100)),
                ("occurred_at", models.DateTimeField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="session_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="sessionevent",
            constraint=models.UniqueConstraint(
                fields=("user", "client_id"),
                name="unique_session_client_id_per_user",
            ),
        ),
    ]
