# Generated by Django 5.1.4 on 2026-07-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sessionevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='extension_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='minutes_extended',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='pause_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='paused_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='planned_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sessionevent',
            name='template_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessionevent',
            name='event_type',
            field=models.CharField(choices=[('completed', 'Completed'), ('skipped', 'Skipped'), ('extended', 'Extended'), ('stopped', 'Stopped')], max_length=10),
        ),
    ]
