# Generated by Django 5.1.4 on 2026-07-26 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sessionevent_unified_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionevent',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
